### ISSUE TITLE
Add information about licensing

### ISSUE THREAD

**Issue by vbauer** [mattsilber/applock#1]

**Comment by mattsilber** [comment]
Sorry, just got back into the country. I've labeled it as Apache 2.0 on Bintray, but not entirely sure where else you believe it should be (if you'd be so kind as to point it out for me, I'd be more than happy to do it)

But I want this to be free to use, modify, whatever for commercial or free use

**Comment by vbauer** [comment]
Thank you for information! Sorry, I thought to find it in README or LICENSE file..

**Comment by mattsilber** [comment]
Ahhh, a License file would probably have been a good idea... My bad... I'll try to add one in the near future.

Thanks for the help!
