### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by karopass** [mattsilber/applock#2]
I am trying to add applock library in one of my android application. I want secure my ShowContentActivity activity with lock before open it. I have found good library here.

My java code for ShowContentActivity is like below now.

public void showContent(View view) {

        Intent intent = new Intent(LockActivity.this, ShowContentActivity.class);
    startActivity(intent);

    }

}

I have followed instruction in library page for implement it. But I am confused and not able to use. Anybody please suggest me how can I create lock and always use it before open my activity ?

Thanks

**Comment by mattsilber** [comment]
This isn't an issue, so I'm going to close this... But...

First, prompt the user to create a pass code before trying to lock the Activity:

```
new CreateLockDialogBuilder(Activity, 
        new LockCreationListener(){
            public void onLockCanceled(){ } // Dialog was closed without entry
            public void onLockSuccessful(){
                doSomethingOnAppLocked();
            }
        })
        .show();
```
After they've locked it, just wrap your Intent in the check dialog:
```
ActionLockingHelper.unlockIfRequired(Activity, new UnlockEventListener(){
        public void onCanceled(){ } // Dialog was closed without entry
        public void onUnlockFailed(String reason){ } // Not called with default Dialog, instead is handled internally
        public void onUnlockSuccessful(){
            Intent intent = new Intent(LockActivity.this, ShowContentActivity.class);
            startActivity(intent);
        }
    });
```
The above was taken directly from the readme on the front page. There's more there if you want to go further into detail.
